# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comodin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calibre', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('forma', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Longitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitud', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_compra', models.FloatField(blank=True, null=True)),
                ('longitud', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60)),
                ('Calibre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Calibre')),
                ('Forma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Forma')),
                ('Longitud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Longitud')),
                ('Marca_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comodin.Marca')),
                ('Material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='Tipo_Producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Tipo_Producto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='Producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Producto'),
        ),
    ]
