# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comodin', '__first__'),
        ('Usuario', '0001_initial'),
        ('Producto', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=True)),
                ('monto', models.PositiveIntegerField(blank=True, null=True)),
                ('saldo', models.PositiveIntegerField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('fechaLimite', models.DateTimeField()),
                ('fechaAprobacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTotal', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=3, null=True)),
                ('noDocumento', models.PositiveIntegerField(blank=True, null=True)),
                ('precioTotal', models.PositiveIntegerField(blank=True, null=True)),
                ('anulada', models.BooleanField(default=False)),
                ('Comodin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comodin.Comodin')),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noDocumento', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='Factura_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transacciones.Factura'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='Producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Producto'),
        ),
        migrations.AddField(
            model_name='credito',
            name='Factura_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transacciones.Factura'),
        ),
        migrations.AddField(
            model_name='credito',
            name='Usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='abonos',
            name='Credito_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transacciones.Credito'),
        ),
    ]
