# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comodin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=True)),
                ('monto', models.PositiveIntegerField()),
                ('saldo', models.PositiveIntegerField()),
                ('finalizado', models.BooleanField(default=True)),
                ('fechaLimite', models.DateTimeField()),
                ('fechaAprobacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTotal', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=3)),
                ('noDocumento', models.PositiveIntegerField()),
                ('precioTotal', models.PositiveIntegerField()),
                ('anulada', models.BooleanField(default=False)),
                ('Comodin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comodin.Comodin')),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noDocumento', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='Factura_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transacciones.Factura'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='Producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Producto'),
        ),
        migrations.AddField(
            model_name='credito',
            name='factura_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transacciones.Factura'),
        ),
        migrations.AddField(
            model_name='credito',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abonos',
            name='credito_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transacciones.Credito'),
        ),
    ]
