# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_remove_usuario_empleado_id'),
        ('Transacciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abonos',
            old_name='credito_id',
            new_name='Credito_id',
        ),
        migrations.RenameField(
            model_name='credito',
            old_name='factura_id',
            new_name='Factura_id',
        ),
        migrations.RemoveField(
            model_name='credito',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='credito',
            name='Usuario_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abonos',
            name='monto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credito',
            name='monto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='saldo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='subTotal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='noDocumento',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='precioTotal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='serie',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='noDocumento',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
