# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0002_auto_20160731_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fechaAprobacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fechaLimite',
            field=models.DateField(),
        ),
    ]
