# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-20 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transacciones', '0003_auto_20160801_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='noDocumento',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
