# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo', models.FloatField()),
                ('horasExtra', models.FloatField()),
                ('bonoIncentivo', models.FloatField()),
                ('igss', models.FloatField()),
                ('isr', models.FloatField()),
                ('anticipos', models.FloatField()),
                ('judiciales', models.FloatField()),
                ('otros', models.FloatField()),
                ('totalDescuento', models.FloatField()),
                ('totalLiquido', models.FloatField()),
                ('Empleado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Empleado')),
            ],
        ),
    ]
