# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 22:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Planillas', '0002_finanzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='finanzas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2016, 10, 1, 22, 53, 52, 869287, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
