# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 23:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Planillas', '0003_finanzas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finanzas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2016, 10, 1, 23, 11, 27, 769792, tzinfo=utc)),
        ),
    ]
