# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planillas', '0004_auto_20161001_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finanzas',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
