# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Planillas', '0005_auto_20161214_1237'),
        ('Planillas', '0005_auto_20161217_1705'),
    ]

    operations = [
    ]
