# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0001_initial'),
        ('Localizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(max_length=45)),
                ('capital', models.FloatField()),
                ('Municipio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localizaciones.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kEntrada', models.FloatField()),
                ('kSalida', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('vale', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mercaderia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('Agencia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agencia.Agencia')),
                ('Producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo', models.IntegerField(blank=True, null=True)),
                ('placa', models.CharField(blank=True, max_length=7, null=True)),
                ('Agencia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agencia.Agencia')),
            ],
        ),
        migrations.AddField(
            model_name='entrega',
            name='Vehiculo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agencia.Vehiculo'),
        ),
    ]
