# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 17:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(max_length=45)),
                ('capital', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kEntrada', models.FloatField()),
                ('kSalida', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('vale', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mercaderia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('Agencia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agencia.Agencia')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo', models.IntegerField(blank=True, null=True)),
                ('placa', models.CharField(blank=True, max_length=7, null=True)),
                ('Agencia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agencia.Agencia')),
            ],
        ),
    ]
