# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Localizaciones', '0001_initial'),
        ('Comodin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comodin',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Localizaciones.Municipio'),
            preserve_default=False,
        ),
    ]
