# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comodin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comodin',
            name='bloqueado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='comodin',
            name='tipo',
            field=models.BooleanField(),
        ),
    ]
