# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comodin', '0002_auto_20160611_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comodin',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
