# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Empleado_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuario.Empleado'),
            preserve_default=False,
        ),
    ]
