# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_usuario_empleado_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Empleado_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuario.Empleado'),
        ),
    ]
